# Uncomment the next line to define a global platform for your project
# 在 Podfile 最顶部添加（不要带其他无关符号）
# platform :ios, '9.0'

target 'FlushteriousQuintrigue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlushteriousQuintrigue
  pod 'Adjust','4.38.4'
  pod 'FBSDKCoreKit', '17.4.0'
end
